---
name: Docker
on:
  build_push:
    branches: master

env:
  IMAGE_NAME: ooklaserver

jobs:
  build_push:
    name: Publish to Docker Hub
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run:
          - docker build -f Dockerfile -t ${{ secrets.hub_user }}/$IMAGE_NAME:$GITHUB_SHA .
          - docker tag ${{ secrets.hub_user }}/$IMAGE_NAME:$GITHUB_SHA ${{ secrets.hub_user }}/$IMAGE_NAME:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.hub_token  }}" | docker login -u ${{ secrets.hub_user }} --password-stdin

      - name: Push Image to Docker Hub
        run:
          - docker images
          - docker push ${{ secrets.hub_user }}/$IMAGE_NAME:$GITHUB_SHA
          - docker push ${{ secrets.hub_user }}/$IMAGE_NAME:latest
